[package]
name = "rift-lang"
version = "2.0.1"
edition = "2021"
authors = ["Zen"]
license = "MIT"
description = "Multi-Language Code Fusion and Deployment Platform"
repository = "https://github.com/zenyaga/rift-lang"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustyline = "14.0"
web3 = "0.19.0"
solana-client = "1.18.0"
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
rusoto_lambda = "0.48.0"
tokio = { version = "1.0", features = ["full"] }
sha2 = "0.10.8"
futures = "0.3.30"
chrono = "0.4.38"
reqwest = { version = "0.11", features = ["blocking", "json"] }
syn = "2.0"
tree-sitter = "0.20.10"
notify = "6.1"
tch = { version = "0.13", optional = true }
thiserror = "1.0"
anyhow = "1.0"

[build-dependencies]
cc = "1.0"

[features]
default = []
tensorflow = ["tch"]

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"

[[bin]]
name = "rift"
path = "src/main.rs"